const EXTRA_MEDIA_DB='xma7-chat-media-v1';
const EXTRA_MEDIA_STORE='media';
const EXTRA_MEDIA_URLS=new Map();

function extraDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(EXTRA_MEDIA_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(EXTRA_MEDIA_STORE))r.result.createObjectStore(EXTRA_MEDIA_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function extraMediaGet(id){const db=await extraDb();return new Promise((resolve,reject)=>{const tx=db.transaction(EXTRA_MEDIA_STORE,'readonly'),r=tx.objectStore(EXTRA_MEDIA_STORE).get(id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
async function extraMediaPut(id,value){const db=await extraDb();return new Promise((resolve,reject)=>{const tx=db.transaction(EXTRA_MEDIA_STORE,'readwrite');tx.objectStore(EXTRA_MEDIA_STORE).put(value,id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
try{navigator.storage?.persist?.().catch(()=>{})}catch{}

function extraExpired(m){if(m.media_server_deleted_at)return true;if(!m.media_expires_at)return false;return Date.now()>Date.parse(m.media_expires_at)}
function extraStoragePath(path){return String(path||'').split('/').map(encodeURIComponent).join('/')}
function extraHumanBytes(n){n=Number(n||0);if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`}
async function extraSha256(blob){const b=await crypto.subtle.digest('SHA-256',await blob.arrayBuffer());return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}

async function extraCompressPhoto(file){let bmp;try{bmp=await createImageBitmap(file)}catch{throw new Error('This photo format cannot be decoded by this browser')};const maxSide=Math.max(bmp.width,bmp.height),scale=maxSide>1920?1920/maxSide:1;const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bmp.width*scale));canvas.height=Math.max(1,Math.round(bmp.height*scale));canvas.getContext('2d').drawImage(bmp,0,0,canvas.width,canvas.height);bmp.close?.();const toBlob=q=>new Promise(r=>canvas.toBlob(r,'image/jpeg',q));let blob=await toBlob(.82);if(blob&&blob.size>5*1024*1024)blob=await toBlob(.68);if(!blob||blob.size>5*1024*1024)throw new Error('Photo is still larger than 5 MB after compression');return {blob,mime:'image/jpeg',ext:'jpg',type:'photo'}}
async function extraPrepareMedia(file){if(file.type.startsWith('image/'))return extraCompressPhoto(file);if(['video/mp4','video/webm','video/quicktime'].includes(file.type)){if(file.size>30*1024*1024)throw new Error('Video exceeds the 30 MB beta limit');return {blob:file,mime:file.type,ext:file.type==='video/webm'?'webm':file.type==='video/quicktime'?'mov':'mp4',type:'video'}}throw new Error('Only photos and MP4/WebM/MOV videos are supported')}

async function extraSendMedia(file){if(!S.channel||!S.route?.userId)throw new Error('Open a Team Chat channel first');const prepared=await extraPrepareMedia(file),id=crypto.randomUUID(),path=`${S.channel.id}/${id}.${prepared.ext}`,sha=await extraSha256(prepared.blob),expires=new Date(Date.now()+24*60*60*1000).toISOString();const storageUrl=`${SUPABASE_URL}/storage/v1/object/xma7-chat-media/${extraStoragePath(path)}`;const up=await fetch(storageUrl,{method:'POST',headers:{apikey:API_KEY,Authorization:`Bearer ${S.token}`,'Content-Type':prepared.mime,'x-upsert':'false'},body:prepared.blob});if(!up.ok)throw new Error((await up.text())||'Media upload failed');const caption=document.getElementById('chat-message')?.value?.trim()||'';try{await api('/rest/v1/chat_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({id,channel_id:S.channel.id,sender_id:S.route.userId,body:caption,message_type:prepared.type,media_path:path,media_mime:prepared.mime,media_size:prepared.blob.size,media_sha256:sha,media_expires_at:expires})});await extraMediaPut(id,{blob:prepared.blob,mime:prepared.mime,sha,storedAt:Date.now()});if(document.getElementById('chat-message'))document.getElementById('chat-message').value='';await loadMessages();render()}catch(e){fetch(storageUrl,{method:'DELETE',headers:{apikey:API_KEY,Authorization:`Bearer ${S.token}`}}).catch(()=>{});throw e}}

async function extraDownloadMedia(m){const local=await extraMediaGet(m.id);if(local)return local;if(extraExpired(m)||!m.media_path)return null;const u=`${SUPABASE_URL}/storage/v1/object/authenticated/xma7-chat-media/${extraStoragePath(m.media_path)}`;const r=await fetch(u,{headers:{apikey:API_KEY,Authorization:`Bearer ${S.token}`}});if(!r.ok)return null;const blob=await r.blob();const sha=await extraSha256(blob);if(m.media_sha256&&sha!==m.media_sha256)throw new Error('Media integrity check failed');const value={blob,mime:m.media_mime||blob.type,sha,storedAt:Date.now()};await extraMediaPut(m.id,value);return value}
function extraOpenBlob(id,value){if(EXTRA_MEDIA_URLS.has(id))URL.revokeObjectURL(EXTRA_MEDIA_URLS.get(id));const u=URL.createObjectURL(value.blob);EXTRA_MEDIA_URLS.set(id,u);window.open(u,'_blank','noopener')}

loadMessages=async function(){if(!S.channel)return;try{S.messages=await api(`/rest/v1/chat_messages?channel_id=eq.${encodeURIComponent(S.channel.id)}&select=id,sender_id,body,created_at,message_type,media_path,media_mime,media_size,media_sha256,media_expires_at,media_server_deleted_at&order=created_at.asc&limit=50`)}catch{S.messages=[]}}

function extraMediaMessageHtml(m){if((m.message_type||'text')==='text')return `<div class="card"><div>${esc(m.body)}</div><div class="muted small">${esc((m.created_at||'').slice(0,16).replace('T',' '))}</div></div>`;const photo=m.message_type==='photo';return `<div class="card" data-extra-media-card="${m.id}"><div class="module"><div class="icon">${photo?'🖼':'🎬'}</div><div><b>${photo?'Photo':'Video'}</b><div class="muted small">${extraHumanBytes(m.media_size)} · server relay ≤24h</div></div></div><div id="extra-preview-${m.id}"></div>${m.body?`<p>${esc(m.body)}</p>`:''}<button class="btn alt" data-extra-media="${m.id}">Checking local copy…</button><div class="muted small">${esc((m.created_at||'').slice(0,16).replace('T',' '))}</div></div>`}

async function extraHydrateMedia(){for(const m of S.messages.filter(x=>(x.message_type||'text')!=='text')){const button=document.querySelector(`[data-extra-media="${CSS.escape(m.id)}"]`),preview=document.getElementById(`extra-preview-${m.id}`);if(!button)continue;let local=await extraMediaGet(m.id);const shouldAuto=(m.message_type==='photo')||(m.message_type==='video'&&navigator.connection?.type==='wifi');if(!local&&!extraExpired(m)&&shouldAuto){try{local=await extraDownloadMedia(m)}catch{}}
if(local){button.textContent='Open local copy';button.dataset.extraMode='open';if(m.message_type==='photo'&&preview&&!preview.dataset.ready){const u=URL.createObjectURL(local.blob);EXTRA_MEDIA_URLS.set('preview-'+m.id,u);preview.innerHTML=`<img src="${u}" alt="Chat photo" style="width:100%;max-height:220px;object-fit:cover;border-radius:14px;margin:8px 0">`;preview.dataset.ready='1'}}else if(extraExpired(m)){button.textContent='Not saved on this device before server cleanup';button.disabled=true}else{button.textContent='Download to this device';button.dataset.extraMode='download'}}}

const extraBaseRenderWorkspace=renderWorkspace;
renderWorkspace=function(){if(S.wtab!=='chat')return extraBaseRenderWorkspace();const ts=tabs([['home','⌂','Home'],['schedule','◫','Schedule'],['work','✓','Work'],['chat','□','Chat'],['more','•••','More']],S.wtab);const body=`<div class="wrap stack"><div class="calendar-head"><div><h2>Team Chat</h2><p class="muted">${esc(S.channel?.name||'No channel')}</p></div><button class="btn alt" style="width:auto" data-action="refresh-chat">↻</button></div><div class="card"><b>24-hour media relay</b><p class="muted small">Downloaded media stays in this PWA profile after the server copy is removed. Android APK additionally auto-saves photos and Wi-Fi videos to app-private local storage.</p><div class="small">Photo ≤5 MB after compression · Video ≤30 MB</div></div>${S.channels.length>1?`<div class="theme-row">${S.channels.slice(0,4).map(c=>`<button class="btn alt" data-channel="${c.id}">${esc(c.name)}</button>`).join('')}</div>`:''}${S.messages.map(extraMediaMessageHtml).join('')||module('💬','No messages yet','Start the team conversation')}${S.channel?`<div class="task-row"><button class="btn alt" style="width:auto" data-extra-action="attach-media">＋</button><input type="file" id="extra-media-file" accept="image/*,video/mp4,video/webm,video/quicktime" hidden><input class="input" id="chat-message" placeholder="Message / media caption"><button class="btn" style="width:auto" data-action="send-message">➤</button></div><div id="extra-media-status" class="muted small"></div>`:''}</div>`;layout(header()+body,ts);queueMicrotask(()=>extraHydrateMedia().catch(()=>{}))}

function extraBreakShortcuts(){try{return JSON.parse(localStorage.getItem('xma7_break_links')||'[]')}catch{return []}}
function extraSaveBreak(v){localStorage.setItem('xma7_break_links',JSON.stringify(v.slice(0,24)))}
function extraBreakHtml(){const items=extraBreakShortcuts();return `<div class="wrap stack"><div><h2>Take a Break ☕</h2><p class="muted">Your shortcuts, stored only in this browser profile.</p></div><div class="card"><b>PWA note</b><p class="muted small">Browsers cannot inspect which native apps are installed. The Android APK uses the full installed-app picker and automatically removes shortcuts when an app is uninstalled. Here you can save web or app deep links.</p></div><div class="metric-grid">${items.map((x,i)=>`<div class="card" style="text-align:center"><button class="btn alt" data-extra-break-open="${i}">${esc(x.name)}</button><button class="btn alt" data-extra-break-remove="${i}" style="margin-top:6px">× Remove</button></div>`).join('')}<div class="card" style="text-align:center"><button class="btn" data-extra-action="add-break">＋ Add Shortcut</button></div></div></div>`}

const EXTRA_CALC={display:'0',acc:null,op:null,replace:true};
function extraCalcApply(a,b,op){if(op==='+')return a+b;if(op==='−')return a-b;if(op==='×')return a*b;if(op==='÷')return b===0?NaN:a/b;return b}
function extraCalcFormat(n){if(!Number.isFinite(n))return 'Error';return String(Number(n.toFixed(10))).slice(0,20)}
function extraCalcKey(k){if(k==='C'){Object.assign(EXTRA_CALC,{display:'0',acc:null,op:null,replace:true});return}if(k==='='){if(EXTRA_CALC.acc!=null&&EXTRA_CALC.op){EXTRA_CALC.display=extraCalcFormat(extraCalcApply(EXTRA_CALC.acc,Number(EXTRA_CALC.display)||0,EXTRA_CALC.op));EXTRA_CALC.acc=null;EXTRA_CALC.op=null;EXTRA_CALC.replace=true}return}if(['+','−','×','÷'].includes(k)){const now=Number(EXTRA_CALC.display)||0;if(EXTRA_CALC.acc!=null&&EXTRA_CALC.op&&!EXTRA_CALC.replace){const r=extraCalcApply(EXTRA_CALC.acc,now,EXTRA_CALC.op);EXTRA_CALC.display=extraCalcFormat(r);EXTRA_CALC.acc=Number.isFinite(r)?r:null}else EXTRA_CALC.acc=now;EXTRA_CALC.op=k;EXTRA_CALC.replace=true;return}if(EXTRA_CALC.display==='Error'||EXTRA_CALC.replace){EXTRA_CALC.display=k==='.'?'0.':k;EXTRA_CALC.replace=false}else if(k==='.'&&!EXTRA_CALC.display.includes('.'))EXTRA_CALC.display+='.';else if(k!=='.'&&EXTRA_CALC.display.length<18)EXTRA_CALC.display=EXTRA_CALC.display==='0'?k:EXTRA_CALC.display+k}
function extraCalcHtml(){const rows=[['7','8','9','÷'],['4','5','6','×'],['1','2','3','−'],['0','.','C','+']];return `<div class="card calculator-card"><div><h3>Basic Calculator</h3><div class="muted small">Quick everyday calculations</div></div><div class="calc-display"><span>${esc(EXTRA_CALC.op?`Operation  ${EXTRA_CALC.op}`:'Ready')}</span><strong>${esc(EXTRA_CALC.display)}</strong></div><div class="calc-grid">${rows.flat().map(k=>`<button class="${['+','−','×','÷'].includes(k)?'btn':'btn alt'} calc-key" data-extra-calc="${k}">${k}</button>`).join('')}</div><button class="btn calc-equals" data-extra-calc="=">=</button></div>`}
function extraPersonalMore(){const work=S.route?.type?button('⇄ Open Workspace','switch-space',true):'',join=S.route&&!S.route.type?button('Join Workplace with invite code','open-join'):'';return `<div class="wrap stack"><h2>More</h2><p class="muted">Private to you.</p>${work}${join}<div class="card"><h3>Theme</h3><div class="theme-row">${['system','day','night'].map(t=>`<button class="btn alt" data-theme-choice="${t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div></div><h3>Toolkit</h3>${extraCalcHtml()}${module('🩺','Procedure reference','High-level clinical checklists')}${module('✓','Personal checklist','Private and independent from workplace data')}${module('🔒','Private local planner','Your planner stays private in this browser profile')}${S.route?button('Sign out','signout',true):''}</div>`}

renderPersonal=function(){const ts=tabs([['today','⌂','Today'],['planner','▦','Planner'],['tasks','✓','Tasks'],['break','☕','Take a Break'],['more','•••','More']],S.ptab);let body='';if(S.ptab==='today')body=personalToday();if(S.ptab==='planner')body=plannerMonth();if(S.ptab==='tasks')body=personalTasks();if(S.ptab==='break')body=extraBreakHtml();if(S.ptab==='more')body=extraPersonalMore();layout(header()+body,ts)}

document.addEventListener('click',async e=>{const attach=e.target.closest('[data-extra-action="attach-media"]');if(attach){document.getElementById('extra-media-file')?.click();return}const add=e.target.closest('[data-extra-action="add-break"]');if(add){const name=prompt('Shortcut name');if(!name)return;const url=prompt('Web or app link (example: https://foodpanda.my)');if(!url)return;const items=extraBreakShortcuts();items.push({name:name.trim().slice(0,40),url:url.trim().slice(0,500)});extraSaveBreak(items);renderPersonal();return}const open=e.target.closest('[data-extra-break-open]');if(open){const item=extraBreakShortcuts()[Number(open.dataset.extraBreakOpen)];if(item)window.open(item.url,'_blank','noopener');return}const remove=e.target.closest('[data-extra-break-remove]');if(remove){const items=extraBreakShortcuts();items.splice(Number(remove.dataset.extraBreakRemove),1);extraSaveBreak(items);renderPersonal();return}const calc=e.target.closest('[data-extra-calc]');if(calc){extraCalcKey(calc.dataset.extraCalc);renderPersonal();return}const media=e.target.closest('[data-extra-media]');if(media){const m=S.messages.find(x=>x.id===media.dataset.extraMedia);if(!m)return;const status=document.getElementById('extra-media-status');try{if(status)status.textContent='Loading local media…';const value=await extraDownloadMedia(m);if(!value){if(status)status.textContent='Server relay copy is no longer available on this device.';await extraHydrateMedia();return}extraOpenBlob(m.id,value);if(status)status.textContent='Local copy retained in this PWA profile.';await extraHydrateMedia()}catch(err){if(status)status.textContent=errorText(err)}return}},true);

document.addEventListener('change',async e=>{if(e.target?.id!=='extra-media-file')return;const file=e.target.files?.[0];if(!file)return;const status=document.getElementById('extra-media-status');try{if(status)status.textContent='Preparing and uploading media…';await extraSendMedia(file)}catch(err){if(status)status.textContent=errorText(err)}finally{e.target.value=''}},true);
