const SUPABASE_URL='https://yzpjditlahoebkwjdhmv.supabase.co';
const API_KEY='sb_publishable_dk8ijXYo7BV6uruhFKAlhw_qakOyc3Y';
const app=document.getElementById('app');
const S={auth:'welcome',route:null,token:null,refreshToken:null,space:'workspace',wtab:'home',ptab:'today',month:new Date(new Date().getFullYear(),new Date().getMonth(),1),selected:null,tasks:[],announcements:[],rosters:[],onCall:[],channels:[],channel:null,messages:[],loading:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const pad=n=>String(n).padStart(2,'0');
const keyDate=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const planner=()=>JSON.parse(localStorage.getItem('xma7_pwa_planner')||'{}');
const savePlanner=v=>localStorage.setItem('xma7_pwa_planner',JSON.stringify(v));
const theme=()=>localStorage.getItem('xma7_theme')||'system';
const session=()=>{try{return JSON.parse(localStorage.getItem('xma7_pwa_session')||'null')}catch{return null}};
const saveSession=(access,refresh)=>{S.token=access||null;S.refreshToken=refresh||null;if(access)localStorage.setItem('xma7_pwa_session',JSON.stringify({access_token:access,refresh_token:refresh}));else localStorage.removeItem('xma7_pwa_session')};
function applyTheme(){const t=theme();const night=t==='night'||(t==='system'&&matchMedia('(prefers-color-scheme:dark)').matches);document.documentElement.dataset.theme=night?'night':'day'}
applyTheme();matchMedia('(prefers-color-scheme:dark)').addEventListener?.('change',()=>{if(theme()==='system')applyTheme()});
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));

function layout(content,tabs=''){app.innerHTML=`<div class="app">${content}${tabs}</div>`}
function button(label,action,alt=false){return `<button class="btn${alt?' alt':''}" data-action="${action}">${esc(label)}</button>`}
function tabs(items,current){return `<nav class="tabs">${items.map(([id,icon,label])=>`<button data-tab="${id}" class="${current===id?'active':''}"><div>${icon}</div>${esc(label)}</button>`).join('')}</nav>`}
function module(icon,title,sub){return `<div class="card module"><div class="icon">${icon}</div><div><b>${esc(title)}</b><div class="muted small">${esc(sub)}</div></div></div>`}
function errorText(e){const x=String(e?.message||e||'Request failed');if(x.includes('XMA7_ACCOUNT_TYPE_MISMATCH'))return 'This account belongs to a different workplace type.';if(x.includes('XMA7_STAFF_LIMIT_REACHED'))return 'This workplace has reached its licensed staff limit.';if(x.includes('XMA7_INVITE_INVALID_OR_EXPIRED'))return 'Invite code is invalid, expired or already used.';if(x.includes('XMA7_WORKPLACE_READ_ONLY'))return 'Workplace license is read-only or expired.';return x.slice(0,180)}

async function api(path,opts={},retry=true){const h={'apikey':API_KEY,'Content-Type':'application/json',...(opts.headers||{})};if(S.token)h.Authorization=`Bearer ${S.token}`;const r=await fetch(SUPABASE_URL+path,{...opts,headers:h});if(r.status===401&&retry&&S.refreshToken){await refreshSession();return api(path,opts,false)}const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data=text}if(!r.ok)throw new Error(data?.msg||data?.message||data?.error_description||data?.error||text||'Request failed');return data}
async function refreshSession(){if(!S.refreshToken)throw new Error('Session expired');const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:API_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:S.refreshToken})});const d=await r.json();if(!r.ok){saveSession(null,null);throw new Error('Session expired')}saveSession(d.access_token,d.refresh_token)}
async function loadRoute(userId){const profiles=await api(`/rest/v1/profiles?user_id=eq.${encodeURIComponent(userId)}&select=display_name,institutional_type`);const memberships=await api(`/rest/v1/workplace_memberships?user_id=eq.${encodeURIComponent(userId)}&status=eq.active&select=workplace_id,roles`);const p=profiles[0]||{};const m=memberships[0];if(!m)return {userId,displayName:p.display_name||'XMA7 User',type:null,roles:[]};const ws=(await api(`/rest/v1/workplaces?id=eq.${encodeURIComponent(m.workplace_id)}&select=id,name,facility_name,institutional_type`))[0];const ums=await api(`/rest/v1/unit_memberships?user_id=eq.${encodeURIComponent(userId)}&active=eq.true&select=unit_id`);let unit=null;if(ums[0])unit=(await api(`/rest/v1/units?id=eq.${encodeURIComponent(ums[0].unit_id)}&select=id,name,unit_type`))[0]||null;return {userId,workplaceId:ws?.id,displayName:p.display_name||'XMA7 User',type:ws?.institutional_type||null,workplaceName:ws?.facility_name||ws?.name||'Workplace',roles:m?.roles||[],unitId:unit?.id||null,unitName:unit?.name||null}}
async function restore(){const s=session();if(!s)return render();saveSession(s.access_token,s.refresh_token);try{const u=await api('/auth/v1/user');S.route=await loadRoute(u.id);S.space=S.route.type?(localStorage.getItem('xma7_last_space')||'workspace'):'personal';S.auth='app';await loadWorkspaceData();render()}catch{try{await refreshSession();const u=await api('/auth/v1/user');S.route=await loadRoute(u.id);S.space=S.route.type?'workspace':'personal';S.auth='app';render()}catch{saveSession(null,null);S.auth='welcome';render()}}}

function render(){if(S.auth==='welcome')return renderWelcome();if(S.auth==='login')return renderLogin();if(S.auth==='register')return renderRegister();if(S.auth==='join')return renderJoin();if(S.auth==='invite')return renderInvite();if(S.auth==='app')return renderApp()}
function renderWelcome(){layout(`<div class="wrap hero stack"><div><div class="logo">XMA7</div><h2>Medical Assistant Companion</h2><p class="muted">Workplace and personal life. Two spaces, one app.</p></div><div class="card primary-card"><h2>Ready for your shift</h2><p>Workspace and personal tools are organised so the things you need stay easy to reach.</p></div>${button('Sign In','login')}${button('Create account','register',true)}${button('Use Personal Space','personal',true)}<p class="muted small" style="text-align:center">v1.1.0-alpha.7 · PWA</p></div>`)}
function renderLogin(){layout(`<div class="wrap hero stack"><button class="btn alt" data-action="back">← Back</button><div><div class="logo">XMA7</div><h2>Welcome back</h2><p class="muted">Sign in once. XMA7 opens the workplace assigned to your account.</p></div><input class="input" id="identity" placeholder="Email / XMA7 ID" autocomplete="username"><input class="input" id="password" type="password" placeholder="Password" autocomplete="current-password">${button('Sign In','submit-login')}<button class="btn alt" data-action="forgot">Forgot password?</button><div id="login-error" class="muted small"></div></div>`)}
function renderRegister(){layout(`<div class="wrap hero stack"><button class="btn alt" data-action="back">← Back</button><h2>Create account</h2><p class="muted">Start with Personal Space. Join your workplace later with an invite code.</p><input class="input" id="reg-email" type="email" placeholder="Email"><input class="input" id="reg-password" type="password" placeholder="Password · minimum 8 characters">${button('Create account','submit-register')}<div id="register-info" class="muted small"></div></div>`)}
function renderJoin(){layout(`<div class="wrap hero stack"><button class="btn alt" data-action="close-subpage">← Back</button><h2>Join Workplace</h2><p class="muted">Enter the one-time invite code provided by your clinic or department administrator.</p><input class="input" id="invite-code" placeholder="Invite code" autocapitalize="characters">${button('Join','submit-join')}<div id="join-error" class="muted small"></div><div class="card"><b>Account type protection</b><p class="muted small">The server rejects an invite if it does not match the institutional type already locked to the account.</p></div></div>`)}
function renderInvite(){layout(`<div class="wrap hero stack"><button class="btn alt" data-action="close-subpage">← Back</button><h2>Invite Staff</h2><p class="muted">Generate a one-time staff invite. Default expiry is 7 days.</p>${button('Generate invite code','generate-invite')}<div id="invite-result"></div></div>`)}

async function signIn(){const identity=document.getElementById('identity').value.trim(),password=document.getElementById('password').value,err=document.getElementById('login-error');err.textContent='Signing in…';try{let email=identity;const id=identity.toUpperCase();if(id==='CLINIC-TESTER'||id==='HOSPITAL-TESTER'){const b=await api('/functions/v1/pilot-bootstrap',{method:'POST',body:JSON.stringify({tester_id:id,password})});email=b.login_email}else if(!identity.includes('@'))throw new Error('Use a valid XMA7 ID or email address');const auth=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})},false);saveSession(auth.access_token,auth.refresh_token);S.route=await loadRoute(auth.user.id);S.space=S.route.type?'workspace':'personal';localStorage.setItem('xma7_last_space',S.space);S.auth='app';await loadWorkspaceData();render()}catch(e){err.textContent=errorText(e)}}
async function register(){const email=document.getElementById('reg-email').value.trim(),password=document.getElementById('reg-password').value,info=document.getElementById('register-info');if(!email.includes('@')||password.length<8){info.textContent='Use a valid email and password with at least 8 characters.';return}info.textContent='Creating…';try{const d=await api('/auth/v1/signup',{method:'POST',body:JSON.stringify({email,password})},false);if(d.access_token)saveSession(d.access_token,d.refresh_token);info.textContent='Account created. Check your email if confirmation is required.'}catch(e){info.textContent=errorText(e)}}
async function forgot(){const identity=document.getElementById('identity').value.trim(),err=document.getElementById('login-error');if(!identity.includes('@')){err.textContent='Enter your email address first.';return}try{await api('/auth/v1/recover',{method:'POST',body:JSON.stringify({email:identity})},false);err.textContent='Password reset email requested.'}catch(e){err.textContent=errorText(e)}}
async function join(){const code=document.getElementById('invite-code').value.trim().toUpperCase(),el=document.getElementById('join-error');el.textContent='Joining…';try{await api('/rest/v1/rpc/redeem_workplace_invite',{method:'POST',body:JSON.stringify({p_token:code})});const u=await api('/auth/v1/user');S.route=await loadRoute(u.id);S.space='workspace';localStorage.setItem('xma7_last_space','workspace');S.auth='app';await loadWorkspaceData();render()}catch(e){el.textContent=errorText(e)}}
async function generateInvite(){const el=document.getElementById('invite-result');el.innerHTML='<p class="muted">Generating…</p>';try{const code=await api('/rest/v1/rpc/create_workplace_invite',{method:'POST',body:JSON.stringify({p_workplace_id:S.route.workplaceId,p_unit_id:S.route.unitId||null,p_roles:['staff'],p_expires_hours:168})});el.innerHTML=`<div class="card primary-card" style="text-align:center"><div class="muted small">Staff invite</div><h2>${esc(code)}</h2><div class="small">One-time use · expires in 7 days</div></div>`}catch(e){el.innerHTML=`<p class="muted">${esc(errorText(e))}</p>`}}
async function signOut(){try{await api('/auth/v1/logout',{method:'POST'})}catch{}saveSession(null,null);S.route=null;S.auth='welcome';S.tasks=[];S.messages=[];render()}

async function loadWorkspaceData(){if(!S.route?.workplaceId)return;try{const w=encodeURIComponent(S.route.workplaceId);const [tasks,anns,rosters,channels]=await Promise.all([api(`/rest/v1/shared_tasks?workplace_id=eq.${w}&select=id,title,note,status,due_at,patient_tag&order=created_at.desc`),api(`/rest/v1/announcements?workplace_id=eq.${w}&select=id,title,body,pinned,created_at&order=pinned.desc,created_at.desc`),api(`/rest/v1/rosters?workplace_id=eq.${w}&status=eq.published&select=id,period_start,period_end,status,version&order=period_start.desc`),api(`/rest/v1/chat_channels?workplace_id=eq.${w}&select=id,name,kind,unit_id&order=created_at.asc`)]);S.tasks=tasks;S.announcements=anns;S.rosters=rosters;S.channels=channels;S.channel=S.channel&&channels.find(c=>c.id===S.channel.id)||channels[0]||null;if(S.channel)await loadMessages()}catch(e){console.warn(e)}}
async function loadMessages(){if(!S.channel)return;try{S.messages=await api(`/rest/v1/chat_messages?channel_id=eq.${encodeURIComponent(S.channel.id)}&select=id,sender_id,body,created_at&order=created_at.asc&limit=50`)}catch{S.messages=[]}}
async function addTask(){const input=document.getElementById('new-team-task');if(!input||!input.value.trim())return;try{await api('/rest/v1/shared_tasks',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({workplace_id:S.route.workplaceId,unit_id:S.route.unitId||null,title:input.value.trim(),created_by:S.route.userId})});input.value='';await loadWorkspaceData();render()}catch(e){alert(errorText(e))}}
async function sendMessage(){const input=document.getElementById('chat-message');if(!input||!input.value.trim()||!S.channel)return;try{await api('/rest/v1/chat_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({channel_id:S.channel.id,sender_id:S.route.userId,body:input.value.trim()})});input.value='';await loadMessages();render()}catch(e){alert(errorText(e))}}

function header(){const personal=S.space==='personal',hasWork=!!S.route?.type;const label=personal?'👤 Personal Space':`${S.route?.type==='clinic'?'🏥':'🏨'} ${esc(S.route?.workplaceName||'Workspace')}`;return `<header class="header"><button class="space-switch" data-action="switch-space" ${hasWork?'':'disabled'}>${label}${hasWork?' &nbsp;⇄':''}</button><span class="grow"></span><span class="muted small">α7</span></header>`}
function renderApp(){if(S.selected)return renderDay();if(S.space==='workspace'&&S.route?.type)return renderWorkspace();return renderPersonal()}
function renderWorkspace(){const ts=tabs([['home','⌂','Home'],['schedule','◫','Schedule'],['work','✓','Work'],['chat','□','Chat'],['more','•••','More']],S.wtab);let body='';const clinic=S.route.type==='clinic';if(S.wtab==='home'){const pending=S.tasks.filter(x=>x.status!=='done').length,pinned=S.announcements.filter(x=>x.pinned).length;body=`<div class="wrap stack"><div><h2>${clinic?'Clinic Workspace':'Hospital Workspace'}</h2><p class="muted">${esc(S.route.unitName||S.route.workplaceName)}</p><p class="muted small inspired">${clinic?'Inspired by Nurul Haziqah Hasan':'Inspired by Nor Hafizah Ramli'}</p></div><div class="card primary-card"><h3>${esc(S.route.displayName)}</h3><p class="muted">${esc((S.route.roles||[]).join(' · ')||'staff')}</p></div><div class="metric-grid"><div class="card metric"><h2>${pending}</h2>Pending tasks</div><div class="card metric"><h2>${pinned}</h2>Pinned updates</div></div>${S.announcements.slice(0,3).map(x=>module('📢',x.title,x.body)).join('')||module('📢','No announcements yet','Team updates will appear here')}</div>`}
if(S.wtab==='schedule')body=`<div class="wrap stack"><h2>Schedule</h2><p class="muted">${clinic?'Published monthly roster and on-call.':'Published unit roster and shifts.'}</p>${S.rosters.map(r=>module('🗓',`${r.period_start} → ${r.period_end}`,`Published · version ${r.version}`)).join('')||module('🗓','No published roster yet','A published roster will appear here.')}</div>`;
if(S.wtab==='work')body=`<div class="wrap stack"><div class="calendar-head"><div><h2>Work</h2><p class="muted">Shared team tasks${S.route.unitName?' · '+esc(S.route.unitName):''}</p></div><button class="btn alt" style="width:auto" data-action="refresh-work">↻</button></div><div class="task-row"><input class="input" id="new-team-task" placeholder="New team task"><button class="btn" style="width:auto" data-action="add-team-task">+</button></div>${S.tasks.map(x=>module('✓',x.title,`${x.status}${x.note?' · '+x.note:''}`)).join('')||module('✓','No team tasks yet','Create the first task above')}</div>`;
if(S.wtab==='chat')body=`<div class="wrap stack"><div class="calendar-head"><div><h2>Team Chat</h2><p class="muted">${esc(S.channel?.name||'No channel')}</p></div><button class="btn alt" style="width:auto" data-action="refresh-chat">↻</button></div>${S.channels.length>1?`<div class="theme-row">${S.channels.slice(0,4).map(c=>`<button class="btn alt" data-channel="${c.id}">${esc(c.name)}</button>`).join('')}</div>`:''}${S.messages.map(m=>`<div class="card"><div>${esc(m.body)}</div><div class="muted small">${esc((m.created_at||'').slice(0,16).replace('T',' '))}</div></div>`).join('')||module('💬','No messages yet','Start the team conversation')}${S.channel?`<div class="task-row"><input class="input" id="chat-message" placeholder="Message"><button class="btn" style="width:auto" data-action="send-message">➤</button></div>`:''}</div>`;
if(S.wtab==='more'){const canInvite=(S.route.roles||[]).some(r=>r==='head'||r==='admin');body=`<div class="wrap stack"><h2>More</h2>${button('⇄ Open Personal Space','switch-space',true)}${canInvite?button('Invite Staff','open-invite'):''}${module('⚙','Settings','Workspace and account settings')}${button('Sign out','signout',true)}</div>`}layout(header()+body,ts)}

function renderPersonal(){const ts=tabs([['today','⌂','Today'],['planner','▦','Planner'],['tasks','✓','Tasks'],['toolkit','▣','Toolkit'],['more','•••','More']],S.ptab);let body='';if(S.ptab==='today')body=personalToday();if(S.ptab==='planner')body=plannerMonth();if(S.ptab==='tasks')body=personalTasks();if(S.ptab==='toolkit')body=`<div class="wrap stack"><h2>Toolkit</h2><p class="muted">Tools live directly in Personal Space. No third dashboard.</p>${module('▣','Quick calculators','BMI and basic counters')}${module('🩺','Procedure reference','High-level clinical checklists')}${module('✓','Personal checklist','Private and independent from workplace data')}</div>`;if(S.ptab==='more')body=personalMore();layout(header()+body,ts)}
function personalToday(){const d=new Date(),k=keyDate(d),p=planner(),day=p[k]||{note:'',entries:[]};const done=day.entries.filter(x=>x.checked).length,pending=day.entries.length-done;return `<div class="wrap stack"><div><h2>Today</h2><p class="muted">${d.toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p></div><div class="card primary-card" data-date="${k}"><h3>Today's plan</h3><p>${pending} Pending · ${done} Done</p>${day.entries.slice(0,3).map(x=>`<div>${x.checked?'✓':'□'} ${esc(x.text)}</div>`).join('')}</div>${button('▦ Open monthly planner','planner')}<p class="muted">Plan work, family, appointments and everyday life in one private space.</p></div>`}
function plannerMonth(){const y=S.month.getFullYear(),m=S.month.getMonth(),first=new Date(y,m,1),offset=(first.getDay()+6)%7,last=new Date(y,m+1,0).getDate(),p=planner(),today=keyDate(new Date());let cells='';for(let i=0;i<42;i++){const n=i-offset+1;if(n<1||n>last){cells+='<div></div>';continue}const d=new Date(y,m,n),k=keyDate(d),day=p[k]||{entries:[],note:''};cells+=`<div class="day ${k===today?'today':''}" data-date="${k}"><div class="n">${n}</div>${(day.entries||[]).slice(0,2).map(x=>`<div class="preview">${x.checked?'✓':'□'} ${esc(x.text)}</div>`).join('')}${!day.entries?.length&&day.note?`<div class="preview">✎ ${esc(day.note)}</div>`:''}${(day.entries?.length||0)>2?`<div class="preview">+${day.entries.length-2}</div>`:''}</div>`}return `<div class="wrap stack"><div class="calendar-head"><button class="btn alt" data-action="prev-month">‹</button><div style="text-align:center"><h2>${S.month.toLocaleDateString(undefined,{month:'long'})}</h2><div class="muted">${y}</div></div><button class="btn alt" data-action="next-month">›</button></div><div class="weekdays">${['M','T','W','T','F','S','S'].map(x=>`<div>${x}</div>`).join('')}</div><div class="calendar-grid">${cells}</div></div>`}
function personalTasks(){const p=planner(),all=[];Object.entries(p).forEach(([date,day])=>(day.entries||[]).forEach(x=>all.push({...x,date})));return `<div class="wrap stack"><h2>Tasks</h2><p class="muted">Planner tasks appear here automatically.</p>${all.length?all.sort((a,b)=>a.date.localeCompare(b.date)).map(x=>`<div class="card" data-date="${x.date}">${x.checked?'✓':'□'} ${esc(x.text)}<div class="muted small">${x.date}</div></div>`).join(''):'<div class="card">No personal tasks yet.</div>'}</div>`}
function personalMore(){const work=S.route?.type?button('⇄ Open Workspace','switch-space',true):'',join=S.route&&!S.route.type?button('Join Workplace with invite code','open-join'):'';return `<div class="wrap stack"><h2>More</h2><p class="muted">Private to you.</p>${work}${join}<div class="card"><h3>Theme</h3><div class="theme-row">${['system','day','night'].map(t=>`<button class="btn alt" data-theme-choice="${t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div></div>${module('🔒','Private local planner','Planner stays inside this browser profile')}${S.route?button('Sign out','signout',true):''}</div>`}
function renderDay(){const p=planner(),day=p[S.selected]||{note:'',entries:[]};layout(`<div class="wrap hero editor"><button class="btn alt" data-action="close-day">← Back</button><div><h2>${new Date(S.selected+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})}</h2><p class="muted">Daily Page</p></div><div class="task-row"><input class="input" id="new-task" placeholder="Add planner item"><button class="btn" style="width:auto" data-action="add-task">+</button></div><div class="stack">${(day.entries||[]).map((x,i)=>`<div class="card task-row"><input type="checkbox" data-check="${i}" ${x.checked?'checked':''}><span>${esc(x.text)}</span><button class="btn alt" style="width:auto" data-delete="${i}">×</button></div>`).join('')}</div><textarea class="input" id="day-note" rows="6" placeholder="Type anything here">${esc(day.note||'')}</textarea><p class="muted small">Planner data remains private to this browser profile.</p></div>`)}
function switchSpace(){if(!S.route?.type)return;S.space=S.space==='workspace'?'personal':'workspace';localStorage.setItem('xma7_last_space',S.space);render()}
function saveDayPatch(fn){const p=planner(),day=p[S.selected]||{note:'',entries:[]};fn(day);p[S.selected]=day;if(!day.note&&!day.entries.length)delete p[S.selected];savePlanner(p);renderDay()}

document.addEventListener('click',async e=>{const a=e.target.closest('[data-action]');if(a){const x=a.dataset.action;if(x==='login'){S.auth='login';render()}else if(x==='register'){S.auth='register';render()}else if(x==='back'){S.auth='welcome';render()}else if(x==='close-subpage'){S.auth='app';render()}else if(x==='personal'){S.route=null;S.space='personal';S.auth='app';render()}else if(x==='submit-login')await signIn();else if(x==='submit-register')await register();else if(x==='forgot')await forgot();else if(x==='open-join'){S.auth='join';render()}else if(x==='submit-join')await join();else if(x==='open-invite'){S.auth='invite';render()}else if(x==='generate-invite')await generateInvite();else if(x==='switch-space')switchSpace();else if(x==='signout')await signOut();else if(x==='planner'){S.ptab='planner';render()}else if(x==='prev-month'){S.month=new Date(S.month.getFullYear(),S.month.getMonth()-1,1);render()}else if(x==='next-month'){S.month=new Date(S.month.getFullYear(),S.month.getMonth()+1,1);render()}else if(x==='close-day'){S.selected=null;render()}else if(x==='add-task'){const v=document.getElementById('new-task').value.trim();if(v)saveDayPatch(d=>{d.entries=d.entries||[];d.entries.push({text:v,checked:false})})}else if(x==='refresh-work'){await loadWorkspaceData();render()}else if(x==='add-team-task')await addTask();else if(x==='refresh-chat'){await loadMessages();render()}else if(x==='send-message')await sendMessage()}
const tab=e.target.closest('[data-tab]');if(tab){if(S.space==='workspace')S.wtab=tab.dataset.tab;else S.ptab=tab.dataset.tab;if(S.wtab==='chat')await loadWorkspaceData();render()}
const d=e.target.closest('[data-date]');if(d&&!e.target.closest('button,input')){S.selected=d.dataset.date;render()}
const ch=e.target.closest('[data-channel]');if(ch){S.channel=S.channels.find(c=>c.id===ch.dataset.channel)||S.channel;await loadMessages();render()}
const th=e.target.closest('[data-theme-choice]');if(th){localStorage.setItem('xma7_theme',th.dataset.themeChoice);applyTheme();render()}
const del=e.target.closest('[data-delete]');if(del&&S.selected)saveDayPatch(d=>d.entries.splice(Number(del.dataset.delete),1))});
document.addEventListener('change',e=>{if(e.target.matches('[data-check]')&&S.selected)saveDayPatch(d=>{const i=Number(e.target.dataset.check);if(d.entries[i])d.entries[i].checked=e.target.checked})});
document.addEventListener('input',e=>{if(e.target.id==='day-note'&&S.selected){const p=planner(),d=p[S.selected]||{note:'',entries:[]};d.note=e.target.value;p[S.selected]=d;savePlanner(p)}});

restore();
