const SUPABASE_URL='https://yzpjditlahoebkwjdhmv.supabase.co';
const API_KEY='sb_publishable_dk8ijXYo7BV6uruhFKAlhw_qakOyc3Y';
const app=document.getElementById('app');
const S={auth:'welcome',route:null,token:null,space:'workspace',wtab:'home',ptab:'today',month:new Date(new Date().getFullYear(),new Date().getMonth(),1),selected:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const pad=n=>String(n).padStart(2,'0');
const keyDate=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const planner=()=>JSON.parse(localStorage.getItem('xma7_pwa_planner')||'{}');
const savePlanner=v=>localStorage.setItem('xma7_pwa_planner',JSON.stringify(v));
const theme=()=>localStorage.getItem('xma7_theme')||'system';
function applyTheme(){const t=theme();const night=t==='night'||(t==='system'&&matchMedia('(prefers-color-scheme:dark)').matches);document.documentElement.dataset.theme=night?'night':'day'}
applyTheme();matchMedia('(prefers-color-scheme:dark)').addEventListener?.('change',()=>{if(theme()==='system')applyTheme()});
if('serviceWorker'in navigator) addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));

function layout(content,tabs=''){app.innerHTML=`<div class="app">${content}${tabs}</div>`;}
function button(label,action,alt=false){return `<button class="btn${alt?' alt':''}" data-action="${action}">${label}</button>`}
function tabs(items,current){return `<nav class="tabs">${items.map(([id,icon,label])=>`<button data-tab="${id}" class="${current===id?'active':''}"><div>${icon}</div>${label}</button>`).join('')}</nav>`}
function module(icon,title,sub){return `<div class="card module"><div class="icon">${icon}</div><div><b>${esc(title)}</b><div class="muted small">${esc(sub)}</div></div></div>`}

function render(){
 if(S.auth==='welcome') return renderWelcome();
 if(S.auth==='login') return renderLogin();
 if(S.auth==='register') return renderRegister();
 if(S.auth==='app') return renderApp();
}
function renderWelcome(){layout(`<div class="wrap hero stack"><div><div class="logo">XMA7</div><h2>Medical Assistant Companion</h2><p class="muted">Work and personal life. Two spaces, one app.</p></div><div class="card primary-card"><h2>Workspace ↔ Personal</h2><p>No extra dashboard. Switch directly between team work and your private daily planner.</p></div>${button('Sign In','login')}${button('Use Personal Space','personal',true)}<button class="btn alt" data-action="register">Create account</button><p class="muted small" style="text-align:center">v1.1.0-alpha.5 · PWA pilot</p></div>`)}
function renderLogin(){layout(`<div class="wrap hero stack"><button class="btn alt" data-action="back">← Back</button><div><div class="logo">XMA7</div><h2>Welcome back</h2><p class="muted">Sign in once. XMA7 opens the workplace assigned to your account.</p></div><input class="input" id="identity" placeholder="Email / XMA7 ID" autocomplete="username"><input class="input" id="password" type="password" placeholder="Password" autocomplete="current-password">${button('Sign In','submit-login')}<div id="login-error" class="muted small"></div></div>`)}
function renderRegister(){layout(`<div class="wrap hero stack"><button class="btn alt" data-action="back">← Back</button><h2>Create account</h2><p class="muted">Personal-first account registration is available in the Android build. PWA registration UI will be connected after pilot validation.</p>${button('Back to Sign In','login')}</div>`)}

async function api(path,opts={}){const h={'apikey':API_KEY,'Content-Type':'application/json',...(opts.headers||{})};if(S.token)h.Authorization=`Bearer ${S.token}`;const r=await fetch(SUPABASE_URL+path,{...opts,headers:h});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data=text}if(!r.ok)throw new Error(data?.msg||data?.message||data?.error_description||data?.error||'Request failed');return data}
async function signIn(){const identity=document.getElementById('identity').value.trim();const password=document.getElementById('password').value;const err=document.getElementById('login-error');err.textContent='Signing in…';try{let email=identity;const id=identity.toUpperCase();if(id==='CLINIC-TESTER'||id==='HOSPITAL-TESTER'){const b=await api('/functions/v1/pilot-bootstrap',{method:'POST',body:JSON.stringify({tester_id:id,password})});email=b.login_email}else if(!identity.includes('@'))throw new Error('Use a valid XMA7 ID or email address');const auth=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});S.token=auth.access_token;localStorage.setItem('xma7_pwa_token',S.token);const user=auth.user;const profiles=await api(`/rest/v1/profiles?user_id=eq.${encodeURIComponent(user.id)}&select=display_name,institutional_type`);const memberships=await api(`/rest/v1/workplace_memberships?user_id=eq.${encodeURIComponent(user.id)}&select=workplace_id,roles`);const p=profiles[0]||{};const m=memberships[0];let workplace=null;if(m) {const ws=await api(`/rest/v1/workplaces?id=eq.${encodeURIComponent(m.workplace_id)}&select=id,name,facility_name,institutional_type`);workplace=ws[0]||null}S.route={type:(p.institutional_type||'').toLowerCase()||null,displayName:p.display_name||'XMA7 User',workplaceName:workplace?.facility_name||workplace?.name||'Workplace',roles:m?.roles||[]};S.space=S.route.type?'workspace':'personal';S.auth='app';localStorage.setItem('xma7_last_space',S.space);render()}catch(e){err.textContent=e.message}}

function header(){const personal=S.space==='personal';const hasWork=!!S.route?.type;const label=personal?'👤 Personal Space':`${S.route?.type==='clinic'?'🏥':'🏨'} ${esc(S.route?.workplaceName||'Workspace')}`;return `<header class="header"><button class="space-switch" data-action="switch-space" ${hasWork?'':'disabled'}>${label}${hasWork?' &nbsp;⇄':''}</button><span class="grow"></span><span class="muted small">α5</span></header>`}
function renderApp(){if(S.selected)return renderDay();if(S.space==='workspace'&&S.route?.type)return renderWorkspace();return renderPersonal()}
function renderWorkspace(){const ts=tabs([['home','⌂','Home'],['schedule','◫','Schedule'],['work','✓','Work'],['chat','□','Chat'],['more','•••','More']],S.wtab);let body='';const clinic=S.route.type==='clinic';if(S.wtab==='home')body=`<div class="wrap stack"><div><h2>${clinic?'Clinic Workspace':'Hospital Workspace'}</h2><p class="muted">${esc(S.route.workplaceName)}</p></div><div class="card primary-card"><h3>${esc(S.route.displayName)}</h3><p class="muted">${esc((S.route.roles||[]).join(' · '))}</p></div><div class="metric-grid"><div class="card metric"><h2>—</h2>${clinic?'On-call today':'Staff on shift'}</div><div class="card metric"><h2>—</h2>${clinic?'Staff on duty':'Handover'}</div></div>${module('🗓',clinic?'Monthly roster':'Weekly roster','Latest published roster')}${module('✓','Team tasks','Pending')}${module('📢','Announcements','Latest team updates')}</div>`;
 if(S.wtab==='schedule')body=`<div class="wrap stack"><h2>Schedule</h2>${module('🗓',clinic?'Monthly roster':'Weekly roster','Latest published roster')}${module('◷',clinic?'On-call today':'Shift','Current schedule')}${module('👥',clinic?'Staff on duty':'Staff on shift','Today team')}</div>`;
 if(S.wtab==='work')body=`<div class="wrap stack"><h2>Work</h2><p class="muted">Shift, handover and team work live here. No third dashboard.</p>${module('◷','Shift','Shift overview')}${module('☑','Handover','Pending action')}${module('✓','Team tasks','Pending')}${module('▣','Shared stock & equipment','Management')}</div>`;
 if(S.wtab==='chat')body=`<div class="wrap stack"><h2>Chat</h2>${module('💬','Team chat','Team channel')}${module('📢','Announcements','Pinned updates')}</div>`;
 if(S.wtab==='more')body=`<div class="wrap stack"><h2>More</h2>${button('⇄ Open Personal Space','switch-space',true)}${module('⚙','Settings','Workspace settings')}${button('Sign out','signout',true)}</div>`;
 layout(header()+body,ts)}

function renderPersonal(){const ts=tabs([['today','⌂','Today'],['planner','▦','Planner'],['tasks','✓','Tasks'],['toolkit','▣','Toolkit'],['more','•••','More']],S.ptab);let body='';if(S.ptab==='today')body=personalToday();if(S.ptab==='planner')body=plannerMonth();if(S.ptab==='tasks')body=personalTasks();if(S.ptab==='toolkit')body=`<div class="wrap stack"><h2>Toolkit</h2><p class="muted">Tools live directly in Personal Space. The legacy third Dashboard is retired.</p>${module('▣','Calculators','BMI, pulse and respiratory counters')}${module('🩺','Procedure reference','Clinical reference checklists')}${module('✓','Quick checklist','Private personal checklist')}</div>`;if(S.ptab==='more')body=personalMore();layout(header()+body,ts)}
function personalToday(){const d=new Date(),k=keyDate(d),p=planner(),day=p[k]||{note:'',entries:[]};const done=day.entries.filter(x=>x.checked).length,pending=day.entries.length-done;return `<div class="wrap stack"><div><h2>Today</h2><p class="muted">${d.toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p></div><div class="card primary-card" data-date="${k}"><h3>Today's plan</h3><p>${pending} Pending · ${done} Done</p>${day.entries.slice(0,3).map(x=>`<div>${x.checked?'✓':'□'} ${esc(x.text)}</div>`).join('')}</div>${button('▦ Open monthly planner','planner')} ${module('↻','Habits & recurring','Alpha.5 foundation for daily habits and recurring planner items')}<p class="muted">Plan work, family, appointments and everyday life in one private space.</p></div>`}
function plannerMonth(){const y=S.month.getFullYear(),m=S.month.getMonth(),first=new Date(y,m,1),offset=(first.getDay()+6)%7,last=new Date(y,m+1,0).getDate(),p=planner(),today=keyDate(new Date());let cells='';for(let i=0;i<42;i++){const n=i-offset+1;if(n<1||n>last){cells+='<div></div>';continue}const d=new Date(y,m,n),k=keyDate(d),day=p[k]||{entries:[],note:''};cells+=`<div class="day ${k===today?'today':''}" data-date="${k}"><div class="n">${n}</div>${(day.entries||[]).slice(0,2).map(x=>`<div class="preview">${x.checked?'✓':'□'} ${esc(x.text)}</div>`).join('')}${!day.entries?.length&&day.note?`<div class="preview">✎ ${esc(day.note)}</div>`:''}${(day.entries?.length||0)>2?`<div class="preview">+${day.entries.length-2}</div>`:''}</div>`}return `<div class="wrap stack"><div class="calendar-head"><button class="btn alt" data-action="prev-month">‹</button><div style="text-align:center"><h2>${S.month.toLocaleDateString(undefined,{month:'long'})}</h2><div class="muted">${y}</div></div><button class="btn alt" data-action="next-month">›</button></div><div class="weekdays">${['M','T','W','T','F','S','S'].map(x=>`<div>${x}</div>`).join('')}</div><div class="calendar-grid">${cells}</div></div>`}
function personalTasks(){const p=planner(),all=[];Object.entries(p).forEach(([date,day])=>(day.entries||[]).forEach(x=>all.push({...x,date})));return `<div class="wrap stack"><h2>Tasks</h2><p class="muted">Planner tasks appear here automatically.</p>${all.length?all.sort((a,b)=>a.date.localeCompare(b.date)).map(x=>`<div class="card" data-date="${x.date}">${x.checked?'✓':'□'} ${esc(x.text)}<div class="muted small">${x.date}</div></div>`).join(''):'<div class="card">No personal tasks yet.</div>'}</div>`}
function personalMore(){const work=S.route?.type?button(`⇄ ${S.route.type==='clinic'?'Clinic Workspace':'Hospital Workspace'}`,'switch-space',true):'';return `<div class="wrap stack"><h2>More</h2><p class="muted">Private to you.</p>${work}<div class="card"><h3>Theme</h3><div class="theme-row">${['system','day','night'].map(t=>`<button class="btn alt" data-theme-choice="${t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div></div>${module('🔒','Private local planner','PWA planner stays in this browser profile')}${S.route?button('Sign out','signout',true):''}</div>`}
function renderDay(){const p=planner(),day=p[S.selected]||{note:'',entries:[]};layout(`<div class="wrap hero editor"><button class="btn alt" data-action="close-day">← Back</button><div><h2>${new Date(S.selected+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})}</h2><p class="muted">Daily Page</p></div><div class="task-row"><input class="input" id="new-task" placeholder="Add planner item"><button class="btn" style="width:auto" data-action="add-task">+</button></div><div id="day-tasks" class="stack">${(day.entries||[]).map((x,i)=>`<div class="card task-row"><input type="checkbox" data-check="${i}" ${x.checked?'checked':''}><span>${esc(x.text)}</span><button class="btn alt" style="width:auto" data-delete="${i}">×</button></div>`).join('')}</div><textarea class="input" id="day-note" rows="6" placeholder="Type anything here">${esc(day.note||'')}</textarea><p class="muted small">Writing canvas remains available in the Android alpha.5 build. PWA handwriting is scheduled after dual-space pilot validation.</p></div>`)}

function switchSpace(){if(!S.route?.type)return;S.space=S.space==='workspace'?'personal':'workspace';localStorage.setItem('xma7_last_space',S.space);render()}
function saveDayPatch(fn){const p=planner(),day=p[S.selected]||{note:'',entries:[]};fn(day);p[S.selected]=day;if(!day.note&&!day.entries.length)delete p[S.selected];savePlanner(p);renderDay()}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){const x=a.dataset.action;if(x==='login'){S.auth='login';render()}if(x==='register'){S.auth='register';render()}if(x==='back'){S.auth='welcome';render()}if(x==='personal'){S.route=null;S.space='personal';S.auth='app';render()}if(x==='submit-login')signIn();if(x==='switch-space')switchSpace();if(x==='signout'){S.route=null;S.token=null;localStorage.removeItem('xma7_pwa_token');S.auth='welcome';render()}if(x==='planner'){S.ptab='planner';render()}if(x==='prev-month'){S.month=new Date(S.month.getFullYear(),S.month.getMonth()-1,1);render()}if(x==='next-month'){S.month=new Date(S.month.getFullYear(),S.month.getMonth()+1,1);render()}if(x==='close-day'){S.selected=null;render()}if(x==='add-task'){const input=document.getElementById('new-task');const text=input.value.trim();if(text)saveDayPatch(d=>d.entries.push({id:Date.now(),text,checked:false}))}}
 const tab=e.target.closest('[data-tab]');if(tab){if(S.space==='workspace')S.wtab=tab.dataset.tab;else S.ptab=tab.dataset.tab;render()}
 const date=e.target.closest('[data-date]');if(date){S.selected=date.dataset.date;render()}
 const del=e.target.closest('[data-delete]');if(del){saveDayPatch(d=>d.entries.splice(Number(del.dataset.delete),1))}
 const tc=e.target.closest('[data-theme-choice]');if(tc){localStorage.setItem('xma7_theme',tc.dataset.themeChoice);applyTheme();render()}
});
document.addEventListener('change',e=>{if(e.target.matches('[data-check]'))saveDayPatch(d=>{d.entries[Number(e.target.dataset.check)].checked=e.target.checked});if(e.target.id==='day-note')saveDayPatch(d=>d.note=e.target.value)});
render();
