#!/usr/bin/env python3
from pathlib import Path

src=Path('infra/fujitsu-dashboard/index.html')
out=Path('/tmp/redmi-dashboard-index.html')
s=src.read_text()
s=s.replace('Fujitsu','Redmi').replace('FUJITSU','REDMI').replace('fujitsu','redmi')
s=s.replace('free WSL root','free Ubuntu root').replace('WSL IP','Build IP')
s=s.replace('live every 2s','live every 1s')
s=s.replace("setInterval(tick,2000)","setInterval(tick,1000)")

extra_css='''\n<style id="redmi-v3-extra">\n.timeline{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.spark{height:92px;border:1px solid #1d2a39;border-radius:12px;background:linear-gradient(180deg,rgba(53,212,255,.035),rgba(0,0,0,.12));padding:8px;position:relative;overflow:hidden}.spark svg{width:100%;height:58px}.spark polyline{fill:none;stroke:var(--cyan);stroke-width:2;vector-effect:non-scaling-stroke;transition:points .35s}.spark.ram polyline{stroke:var(--orange)}.spark.disk polyline{stroke:var(--green)}.spark.runner polyline{stroke:var(--purple)}.sparkhead{display:flex;justify-content:space-between;gap:8px;font-size:9px;color:var(--muted);margin-bottom:5px}.sparkhead b{color:var(--text);font-size:12px}.historyList{display:flex;flex-direction:column;gap:6px;max-height:330px;overflow:auto}.hist{display:grid;grid-template-columns:minmax(150px,1.4fr) minmax(150px,1.4fr) 100px 90px 110px;gap:8px;align-items:center;border:1px solid #1d2a39;border-radius:10px;padding:8px;background:#0a1017;font-size:9px}.hist b{font-size:10px}.hist .ok{color:var(--green)}.hist .fail{color:var(--red)}.hist .other{color:var(--yellow)}.progressbar{height:5px;border-radius:999px;background:#182430;overflow:hidden;margin-top:7px}.progressbar>i{display:block;height:100%;background:linear-gradient(90deg,var(--cyan),var(--orange));transition:width .6s;width:0}.metric.procMetric .big,.metric.utilMetric .big{margin-top:18px}@media(max-width:900px){.timeline{grid-template-columns:1fr 1fr}.hist{grid-template-columns:1fr 1fr 70px}.hist .hideSmall{display:none}}@media(max-width:620px){.timeline{grid-template-columns:1fr}.hist{grid-template-columns:1fr 70px}.hist .mobileHide{display:none}}\n</style>\n'''
s=s.replace('</head>',extra_css+'</head>')

metric_insert='''\n  <div class="metric procMetric"><div class="label">Processes</div><div id="procCount" class="big">0</div><div class="small">live Linux processes</div></div>\n  <div class="metric utilMetric"><div class="label">Runner Utilization</div><div id="runnerUtil" class="big">0%</div><div class="small"><span id="runnerBusyNow">0</span> active of <span id="runnerTotalNow">0</span></div></div>\n'''
needle='</section>\n\n<section class="panel hermesPanel">'
s=s.replace(needle,metric_insert+'</section>\n\n<section class="panel hermesPanel">',1)

panels='''\n<section class="panel" style="margin-top:10px"><div class="head"><h2>Live Performance Timeline</h2><span class="count">1s sampling · browser-local 2 minute window</span></div><div class="timeline">\n<div class="spark"><div class="sparkhead"><span>CPU</span><b id="cpuNow">0%</b></div><svg viewBox="0 0 100 50" preserveAspectRatio="none"><polyline id="cpuSpark" points="0,50 100,50"/></svg></div>\n<div class="spark ram"><div class="sparkhead"><span>RAM</span><b id="ramNow">0%</b></div><svg viewBox="0 0 100 50" preserveAspectRatio="none"><polyline id="ramSpark" points="0,50 100,50"/></svg></div>\n<div class="spark disk"><div class="sparkhead"><span>DISK</span><b id="diskNow">0%</b></div><svg viewBox="0 0 100 50" preserveAspectRatio="none"><polyline id="diskSpark" points="0,50 100,50"/></svg></div>\n<div class="spark runner"><div class="sparkhead"><span>RUNNER BUSY</span><b id="runnerNow">0%</b></div><svg viewBox="0 0 100 50" preserveAspectRatio="none"><polyline id="runnerSpark" points="0,50 100,50"/></svg></div>\n</div></section>\n<section class="panel" style="margin-top:10px"><div class="head"><h2>Runner / Build History</h2><span id="historyCount" class="count">0 events</span></div><div id="historyRows" class="historyList"><div class="empty">Waiting for build history</div></div></section>\n'''
s=s.replace('<section class="network">',panels+'<section class="network">',1)

helpers=r'''\nconst perfHist={cpu:[],ram:[],disk:[],runner:[]};\nfunction pushPerf(k,v){let a=perfHist[k];a.push(Math.max(0,Math.min(100,Number(v)||0)));if(a.length>120)a.shift()}\nfunction spark(id,a){if(!a.length)return;let pts=a.map((v,i)=>`${a.length===1?100:(i/(a.length-1))*100},${50-(v/100)*50}`).join(' ');$(id).setAttribute('points',pts)}\nfunction fmtDur(sec){sec=Number(sec);if(!Number.isFinite(sec)||sec<0)return '-';if(sec<60)return `${sec}s`;if(sec<3600)return `${Math.floor(sec/60)}m ${sec%60}s`;return `${Math.floor(sec/3600)}h ${Math.floor((sec%3600)/60)}m`}\nfunction historyHtml(h){if(!h?.length)return '<div class="empty">No completed build history yet</div>';return h.slice(0,30).map(x=>{let r=(x.result||x.conclusion||'unknown').toLowerCase(),cl=r==='success'?'ok':r==='failure'?'fail':'other';return `<div class="hist"><div><b>${esc(x.repo||'?')}</b></div><div class="mobileHide">${esc(x.workflow||x.workflowName||'?')}</div><div class="${cl}">${esc(r.toUpperCase())}</div><div class="hideSmall">${fmtDur(x.duration)}</div><div class="hideSmall">${esc(x.branch||'-')}</div></div>`}).join('')}\nfunction enrich(d){let s=d.system||{},m=s.memory||{},di=s.disk||{},sum=d.summary||{};let ru=Number(sum.runner_busy_pct ?? ((sum.runner_busy||0)/Math.max(1,sum.runner_total||0)*100));$('procCount').textContent=s.processes??'-';$('runnerUtil').textContent=`${Math.round(ru)}%`;$('runnerBusyNow').textContent=sum.runner_busy||0;$('runnerTotalNow').textContent=sum.runner_total||0;$('cpuNow').textContent=`${Math.round(s.cpu_percent||0)}%`;$('ramNow').textContent=`${Math.round(m.percent||0)}%`;$('diskNow').textContent=`${Math.round(di.percent||0)}%`;$('runnerNow').textContent=`${Math.round(ru)}%`;pushPerf('cpu',s.cpu_percent);pushPerf('ram',m.percent);pushPerf('disk',di.percent);pushPerf('runner',ru);spark('cpuSpark',perfHist.cpu);spark('ramSpark',perfHist.ram);spark('diskSpark',perfHist.disk);spark('runnerSpark',perfHist.runner);$('historyRows').innerHTML=historyHtml(d.history||[]);$('historyCount').textContent=`${(d.history||[]).length} recent events`;document.querySelectorAll('.job').forEach((el,i)=>{let a=(d.runs||[])[i];if(!a)return;let p=Math.max(0,Math.min(100,Number(a.progress)||0));let bar=document.createElement('div');bar.className='progressbar';bar.innerHTML=`<i style="width:${p}%"></i>`;el.firstElementChild?.appendChild(bar)})}\n'''
s=s.replace("const $=id=>document.getElementById(id),C=2*Math.PI*31;", "const $=id=>document.getElementById(id),C=2*Math.PI*31;"+helpers,1)
s=s.replace("$('foot2').textContent=`${location.host||'build.home'} · dashboard v3 · auto runner discovery`}","$('foot2').textContent=`${location.host||'build.home'} · dashboard v3.1 · Raspi UI / Redmi live source`;enrich(d)}",1)
s=s.replace("$('hsub').textContent='No live telemetry from Redmi'","$('hsub').textContent='No live telemetry from Redmi Build'",1)
out.write_text(s)
print(out)
